package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            dockerRegistry {
                id = "PROJECT_EXT_4"
                name = "registry-bahamout"
                url = "https://registry.bahamout.fr"
                userName = "asaidi"
                password = "credentialsJSON:4884a009-a815-486f-9a1a-421b865bb7e6"
            }
        }
    }
}
