package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        add {
            password("CONAN_REMOTE_PASSWORD", "credentialsJSON:d671d816-a36f-4b5e-8349-d6e0e530cf43")
        }
        add {
            password("github.token", "credentialsJSON:22970b48-331b-4543-9a46-825891e2a99c")
        }
    }
}
