package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'TdgVcsRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("TdgVcsRoot")) {
    val expected = GitVcsRoot({
        id("TdgVcsRoot")
        name = "teamcity-Demo :: GitHub"
        url = "%repo.url%"
        branch = "refs/heads/main"
        branchSpec = """
            +:refs/heads/*
            -:refs/tags/*
        """.trimIndent()
        authMethod = password {
            userName = "x-access-token"
            password = "%github.token%"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "x-access-token"
            password = "credentialsJSON:d3a28e96-4adf-436a-bbd6-493d3ba166b5"
        }
    }

}
